export const logos = {
  nssLogoSvg: "/images/logo.svg",
  nssLogoWebP: "/images/nssOrangeLogo.webp",
};

export const navItems = [
  {
    title: "Home",
    link: "/",
    hr: true,
  },
  {
    title: "About",
    link: "/about",
    hr: true,
  },
  // {
  //     title:"admission",
  //     link:"/admission",
  //     hr:true
  // },
  {
    title: "Faculty",
    link: "/faculty",
    hr: true,
  },
  {
    title: "general rules",
    link: "/general-rules",
    hr: true,
  },
  {
    title: "committee",
    link: "/committee",
    hr: true,
  },
  {
    title: "facilities",
    link: "/facilities",
    hr: true,
  },
  {
    title: "news & events",
    link: "/newsandevents",
    hr: true,
  },
  // {
  //   title: "achievements",
  //   link: "/achievements",
  //   hr: true,
  // },
  {
    title: "Gallery",
    link: "/gallery",
    hr: true,
  },
  {
    title: "Contact",
    link: "/contact",
    hr: false,
  },
];

export const DisciplinaryRules = [
  "Students should develop healthy habits of mind and body by constant self-discipline.",
  "School Uniform is compulsory for the students when they are in the school campus and it should be strictly in accordance with the pattern prescribed by the school.",
  "All must come to school on time. Late comers will have to get a written permission from the Principal to enter into the class.",
  "At the warning bell (8.45am) students should proceed to their classes and remainsilent. Nobody should be seen roaming around after the first bell.",
  "Perfect silence and order should be maintained by the pupils while going out for the assembly and returning to class.",
  "Students should stand in reverence during the prayer time.",
  "All the students should greet teachers, elders and one another especially when they are in the school campus.",
  "Students are expected to speak only English in the school bus and in the school premises.",
  "The students should always speak and behave politely and decently especially when they are out of the campus and while using the public conveyance.",
  "Students should feel it below their dignity to wander about or use filthy language.",
  "Students should bring their handbook daily and it should be shown to the authorities on demand.",
];

export const colors = {
  secondary: "#FFBF78",
  primary: "#FF7D29",
  fontPrimary: "#3d3d3d",
  fontSecondary: "#6d6d6d",
  white: "#fff",
  primary_50: "#fff6ed",
  primary_100: "#ffebd4",
  primary_200: "#ffd2a8",
  primary_300: "#ffb271",
  primary_400: "#ff7d29",
  primary_500: "#fe6411",
  primary_600: "#ef4a07",
  primary_700: "#c63408",
  primary_800: "#9d2b0f",
  primary_900: "#7e2610",
  primary_950: "#440f06",
};

export const galleryImages = [
  { imgPath: "/images/gallery/nss_gallery_images (1).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (2).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (3).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (4).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (5).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (6).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (7).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (8).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (9).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (10).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (11).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (12).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (13).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (14).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (15).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (16).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (17).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (18).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (19).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (20).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (21).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (22).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (23).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (24).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (25).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (26).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (27).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (28).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (29).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (30).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (31).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (32).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (33).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (34).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (35).webp", isLarge: true },
  { imgPath: "/images/gallery/nss_gallery_images (36).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (37).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (38).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (39).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (40).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (41).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (42).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (43).webp", isLarge: false },
  { imgPath: "/images/gallery/nss_gallery_images (44).webp", isLarge: false },
];
